package com.Pagoda.Common.Enums;

public enum Permission {
    READ_PROJECT_METADATA,
    WRITE_PROJECT_METADATA,
    READ_PROJECT_CONTENTS,
    WRITE_PROJECT_CONTENTS,
    READ_ENTERPRISES,
    WRITE_ENTERPRISES,
    READ_ENTERPRISE_USERS,
    WRITE_ENTERPRISE_USERS,
    READ_ENTERPRISE_USER_ROLES,
    WRITE_ENTERPRISE_USER_ROLES,
    TRAIN_PROJECT,
    PUBLISH_PROJECT,
    CALL_PROJECT
}
